using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Impstation.Traits; // imp
using Robust.Shared.Prototypes;
using Content.Shared.Humanoid.Prototypes; // imp

namespace Content.Client.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class TraitPreferenceSelector : Control
{
    public int Cost;

    public bool Preference
    {
        get => Checkbox.Pressed;
        set => Checkbox.Pressed = value;
    }

    // begin imp addition
    public HashSet<ProtoId<SpeciesPrototype>> ExSpecies = [];
    public HashSet<ProtoId<TraitPrototype>> Requires = [];
    public HashSet<ProtoId<TraitPrototype>> Disallows = [];
    public TraitPrototype? Trait = null;
    // end imp addition

    public event Action<bool>? PreferenceChanged;

    public TraitPreferenceSelector(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);

        var text = $"[{trait.Cost}] "; // imp edit -- always display cost, even if it's 0
        text += Loc.GetString(trait.Name);

        Cost = trait.Cost;
        // begin Imp addition
        ExSpecies = trait.ExcludedSpecies;
        Requires = trait.Requires;
        Disallows = trait.Disallows;
        Trait = trait;
        // end Imp addition
        Checkbox.Text = text;
        Checkbox.OnToggled += OnCheckBoxToggled;

        if (trait.Description is { } desc)
        {
            Checkbox.ToolTip = Loc.GetString(desc);
        }
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        PreferenceChanged?.Invoke(Preference);
    }
}
